version: "3.8"

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '8011:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3311:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldata:
